version: "3.9"

services:
  minecraft-afk-bot:
    image: ninjayubaraj/minecraft-afk-bot:latest
    container_name: minecraft-afk-bot
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      SERVER_HOST: "example.domain.com"   # change this
      SERVER_PORT: "25565"
      BOT_USERNAME: "AFKBot"              # or omit for default
      BOT_CHUNK: "1"
    restart: unless-stopped
