version: "3.9"

services:
  minecraft-afk-bot:
    image: ninjayubaraj/minecraft-afk-bot:latest
    container_name: minecraft-afk-bot
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      SERVER_HOST: "example.domain.com" # change this
      SERVER_PORT: "25565" # and this
      BOT_USERNAME: "AFKBot" # Default
      BOT_CHUNK: "2"
      MC_VERSION: "false"
      NODE_ENV: production
    restart: unless-stopped
